version: '3.7'

services:

  client:
    container_name: client
    build: ./client
    volumes:
      - './:/app/client'
      - '/app/client/node_modules'
    ports:
      - 3100:3100
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

networks:
  default:
      name: prlweb_default
      driver: bridge