version: '3.3'

services:
  # chat:
  #   container_name: chat
  #   restart: always
  #   build:
  #     context: ./
  #   volumes:
  #     - ./src:/usr/src/app/src
  #   environment:
  #     - PORT=4000
  #     - DATABASE_CONNECTION=postgres
  #     - DATABASE_HOST=postgres
  #     - DATABASE_PORT=5432
  #     - DATABASE_USERNAME=proleum
  #     - DATABASE_PASSWORD=secret
  #     - DATABASE_DATABASE=chat
  #     - JWT_SECRET=secret
  #     - JWT_EXPIRATION_TIME=130s
  #   ports:
  #     - 4000:4000
  #   command: >
  #     bash -c "npm run start:dev"

  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: encr_chat
      POSTGRES_PASSWORD: secret

volumes:
  pgdata:


