version: '3.3'

services:
  chat:
    container_name: chat
    restart: always
    build:
      context: ./
    volumes:
      - ./src:/usr/src/app/src
    environment:
      - PORT=4000
      - DATABASE_CONNECTION=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=proleum
      - DATABASE_PASSWORD=secret
      - DATABASE_DATABASE=chat
      - JWT_SECRET=secret
      - JWT_EXPIRATION_TIME=130s
    ports:
      - 4000:4000
    command: >
      bash -c "npm run start:dev"

networks:
  default:
      name: prlweb_default
      driver: bridge

